### ISSUE TITLE
(Feature request) Improved 3D view entity placement

### ISSUE THREAD

**Issue by c-d-a** [Garux/netradiant-custom#114]
Using undocked layout, double-right-clicking in 3D view brings the 2D view to the front. This is probably unintended and makes some screen layouts unworkable.

It would also be preferrable if the entity appeared close to where the user had started the double-click.
Same with the entity selection menu: it would be more intuitive if the menu appeared at the point of the first click. Currently the first clock locks the cursor, so on the second click the menu appears at the center of the screen.

**Comment by Garux** [comment]
2D window activation is the bug, this is because it's parent of entity menu. Now working on Qt port, so this is the thing to verify.

Suggested entity handling would add extra layer of complication and possible bugs. I guess it's enough practical to process in most cases like now, as you usually navigate in camera before entity placement, so have control over position and cursor is already centered.

**Comment by Garux** [comment]
2D view activation problem doesn't exist in Qt https://github.com/Garux/netradiant-custom/commit/9d3d2040182af8284fe9c6fdf26950cfa738c4f2
