### ISSUE TITLE
Toggle lock by dimension

### ISSUE THREAD

**Issue by EugenyP** [Garux/netradiant-custom#49]
![image](https://user-images.githubusercontent.com/5616093/91150666-e362f000-e6e6-11ea-9c7f-ea7b212c9b80.png)

**Comment by Garux** [comment]
This functionality is implemented as pressing Shift modifier key during drags.  
See menu.help.mouse shortcuts for more.

**Comment by EugenyP** [comment]
need to press Shift modifier key very carefully, otherwise the selection is removed

need separate such buttons

**Comment by Garux** [comment]
Need to press Shift modifier key after mouse been pressed, this is not a problem at all after short use.  
Buttons aren't smart:
* need to think of which axis you want (basically forces thinking in axes, instead of processing visually)
* multiple clicks to alter axis/axes
* spoiling code and interface

**Comment by EugenyP** [comment]
Can be done so that you can disable unnecessary panels
