### ISSUE TITLE
Feature request: Select game on startup

### ISSUE THREAD

**Issue by themuffinator** [Garux/netradiant-custom#62]
Essentially what the title says. In Gtk it pops up with a drop down list of configured games to select - I switch between Q2, Q3 and QL often so it's cumbersome to change game from the settings menu.

**Comment by Garux** [comment]
This checkbox enables what you want
![image](https://user-images.githubusercontent.com/1734117/106647537-1ff11c80-65a0-11eb-9385-c61df693d2c4.png)
It's also available here
![image](https://user-images.githubusercontent.com/1734117/106647596-36977380-65a0-11eb-94fc-46c0b5f26304.png)
It's disabled by default, because people normally map for one game at a time + hardly figure out, that this extra startup dialog is optional.

**Comment by themuffinator** [comment]
How blind can I be? I saw that option but thought nothing of it. Thanks, this can close now :)
